/* emus.js
 *
 * Unscramble e-mail addresses.
 * Parameters:
 *    eMail1 - name to email, such as Webmaster
 *    eMail2 - domain to email, such as liztomsharp.com
 *    displayText - Displayed name, such as Liz and Tom Sharp
 *    subjectText - Default subject line, such as SSC Website feedback
 *
 * Version: 8/26/2008: Code generated by scrambler.hta.
 * Version: 31 March 2010, Tom Sharp
 * See also http://www.pagetutor.com/scrambler/index.html
 */

function unScramble(eMail1,eMail2,displayText,subjectText)
{
    var a,b,c,d;a=eMail1;c=displayText;b=eMail2.substring(0,eMail2.length-5);
    var t="@";
    if (subjectText!="")
    {
        d="?subject="+escape(subjectText);
    }
    else
    {
        d="";
    }
    document.write("<a href=\"ma"+"il"+"to"+":"+a+t+b+d+"\">"+c+"</a>");
}
