# TODO: Slim js files of unused functions
# TODO: Remove unnecessary js inclusion
# TODO: add include for MediaBox header
# TODO: convert all mediabox images to use lightbox include
# TODO: Update MediaBox to Lightbox (https://github.com/lokesh/lightbox2)
# TODO: convert performances in performance.html to program collection, one program at a time
# TODO: create PDF posters for all performances that have only jpg posters
# BUG: "Concerts" on Performances page should be singular for single concerts
# TODO: Add temporary hack to avoid printing times of concerts whose times are not accurately known
# TODO: After historical data is converted, remove gathering performances explicitly from fylp items
# MISSING: Spring 1997 program
# MISSING: programs before Spring 1996
plugins:
 - "jekyll-tidy"

baseurl: "/group/SymCh"

url: "https://web.stanford.edu"

timezone: "America/Los_Angeles"

collections:
    programs:
    fylp:
        output: true

defaults:
    - scope:
        path: ""
        type: "fylp"
      values:
        layout: "fylp"
