plugins:
 - jekyll-tidy

baseurl: /group/SymCh

url: https://web.stanford.edu

timezone: America/Los_Angeles

collections:
    - albums

defaults:
    - scope:
        path: ""
        type: albums
      values:
        director: Other recordings
