# TODO: Slim js files of unused functions
# TODO: Remove unnecessary js inclusion
# TODO: add include for MediaBox header
# TODO: convert all mediabox images to use lightbox include
# TODO: Update MediaBox to Lightbox (https://github.com/lokesh/lightbox2)
# TODO: convert performances in performance.html to program collection, one program at a time
# TODO: create PDF posters for all performances that have only jpg posters
# BUG: "Concerts" on Performances page should be singular for single concerts
plugins:
 - "jekyll-tidy"

baseurl: "/group/SymCh"

url: "https://web.stanford.edu"

timezone: "America/Los_Angeles"

collections:
    albums:
    pieces:
    programs:
    fylp:
        output: true

defaults:
    - scope:
        path: ""
        type: "albums"
      values:
        director: "Other recordings"
        rating: 0
    - scope:
        path: ""
        type: "fylp"
      values:
        layout: "fylp"
